name: CI for Website
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

# cancel currently running jobs if a new version of the branch is pushed
concurrency:
  group: website-ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Precheck:
    uses: alcionai/corso/.github/workflows/_filechange_checker.yml@main

  Website-Build:
    needs: [Precheck]
    environment: Testing
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || needs.precheck.outputs.websitefileschanged == 'true'
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@v3

      - name: Build website image
        run: |
          make buildimage

      - name: Build website
        run: |
          make build
